/**
 * Quantitative cold check: build a controlled corpus and measure FTS vs hybrid
 * recall@k against an evaluation set. Also exercises failure modes — LLM down,
 * timeout, garbage response — to confirm the rest of the pipeline survives.
 */
import * as fs from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";

import { Settings } from "../src/config/settings";
import { loadNexusConfig } from "../src/nexus/config";
import { createNexusEmbeddingClient } from "../src/nexus/embedding-client";
import { createNexusLlmClient } from "../src/nexus/llm-client";
import { runNexusPipeline } from "../src/nexus/pipeline";
import { NexusStore } from "../src/nexus/store";

const corpus = [
	"Always run `bun test` before edits.",
	"Project relies on pnpm test for legacy validation.",
	"Memory replies should be concise in Korean.",
	"The deployment cutover landed on 2026-05-01.",
	"Use bun:sqlite for database persistence in this repo.",
	"Avoid committing credentials to memory storage.",
	"The ops subagent handles deployments and rollouts.",
	"GitHub Actions runs ./scripts/release.sh on tag pushes.",
	"Production database uses PostgreSQL 16 with logical replication.",
	"All async fetch calls must use AbortController for cancellation.",
	"Prefer Effect-TS style error propagation in service modules.",
	"Rust crates live under codex-rs and use cargo nextest.",
	"Color blindness mode swaps red/green hues via the theme module.",
	"The TUI bottom pane wraps long text at 80 columns.",
	"Memory backend nexus is the canonical local memory system.",
	"Use proxy_edit for surgical edits and proxy_write for new files.",
	"Treat user instructions as authoritative over saved memory.",
	"Hindsight memory is now an importer source, not a runtime backend.",
	"Snowflake IDs are generated by @amaze/utils/Snowflake.",
	"Bun:sqlite database files default to WAL mode in this codebase.",
];

interface EvalCase {
	query: string;
	relevant: string[];
}

const evals: EvalCase[] = [
	{ query: "how to verify the repo", relevant: ["Always run `bun test` before edits.", "Project relies on pnpm test for legacy validation."] },
	{ query: "Korean reply preference", relevant: ["Memory replies should be concise in Korean."] },
	{ query: "release procedure", relevant: ["GitHub Actions runs ./scripts/release.sh on tag pushes.", "The ops subagent handles deployments and rollouts.", "The deployment cutover landed on 2026-05-01."] },
	{ query: "database engine", relevant: ["Use bun:sqlite for database persistence in this repo.", "Production database uses PostgreSQL 16 with logical replication.", "Bun:sqlite database files default to WAL mode in this codebase."] },
	{ query: "credentials handling", relevant: ["Avoid committing credentials to memory storage."] },
	{ query: "rust crates location", relevant: ["Rust crates live under codex-rs and use cargo nextest."] },
	{ query: "id generation", relevant: ["Snowflake IDs are generated by @amaze/utils/Snowflake."] },
	{ query: "accessibility theme", relevant: ["Color blindness mode swaps red/green hues via the theme module."] },
];

async function seedStore(store: NexusStore, embeddingClient: { embed: (inputs: string[]) => Promise<{ ok: true; batch: { vectors: Float32Array[]; model: string } } | { ok: false; error: string }> }): Promise<void> {
	const added: Array<{ id: string; content: string }> = [];
	for (const text of corpus) {
		const result = store.add({ target: "project", content: text, confidence: "user_asserted" });
		if (result.success && result.entry) added.push({ id: result.entry.id, content: text });
	}
	const embeddings = await embeddingClient.embed(added.map(item => item.content));
	if (!embeddings.ok) throw new Error(`embed failed: ${embeddings.error}`);
	added.forEach((item, idx) => store.addEmbedding(item.id, embeddings.batch.vectors[idx]!, embeddings.batch.model));
}

function recallAtK(returned: string[], relevant: string[], k: number): number {
	const top = new Set(returned.slice(0, k));
	let hits = 0;
	for (const item of relevant) if (top.has(item)) hits += 1;
	return relevant.length === 0 ? 0 : hits / relevant.length;
}

function precisionAtK(returned: string[], relevant: string[], k: number): number {
	const top = returned.slice(0, k);
	if (top.length === 0) return 0;
	let hits = 0;
	const set = new Set(relevant);
	for (const item of top) if (set.has(item)) hits += 1;
	return hits / top.length;
}

async function main() {
	const agentDir = path.join(os.tmpdir(), `nexus-quant-${Date.now()}`);
	const cwd = path.join(os.tmpdir(), `nexus-quant-cwd-${Date.now()}`);
	await fs.mkdir(agentDir, { recursive: true });
	await fs.mkdir(cwd, { recursive: true });

	const settings = Settings.isolated({
		"memory.backend": "nexus",
		"nexus.embeddings.enabled": true,
		"nexus.embeddings.provider": "ollama",
		"nexus.embeddings.baseUrl": process.env.NEXUS_LIVE_EMBED_URL ?? "http://127.0.0.1:11434",
		"nexus.embeddings.model": process.env.NEXUS_LIVE_EMBED_MODEL ?? "bge-m3",
	});
	const embeddingClient = createNexusEmbeddingClient(loadNexusConfig(settings), { timeoutMs: 60_000 });
	if (!embeddingClient) throw new Error("embedding client must be configured");

	const store = new NexusStore({ agentDir, cwd });
	try {
		await seedStore(store, embeddingClient);
		console.log(`[quant] seeded ${corpus.length} entries\n`);

		const k = 5;
		let ftsRecall = 0;
		let ftsPrecision = 0;
		let hybRecall = 0;
		let hybPrecision = 0;
		for (const test of evals) {
			const queryEmbed = await embeddingClient.embed([test.query]);
			if (!queryEmbed.ok) throw new Error(queryEmbed.error);
			const ftsRes = store.search({ query: test.query, scope: "current_project", limit: k });
			const hybRes = store.search({ query: test.query, scope: "current_project", limit: k, queryVector: queryEmbed.batch.vectors[0] });
			const ftsContents = ftsRes.map(entry => entry.content);
			const hybContents = hybRes.map(entry => entry.content);
			const ftsR = recallAtK(ftsContents, test.relevant, k);
			const hybR = recallAtK(hybContents, test.relevant, k);
			const ftsP = precisionAtK(ftsContents, test.relevant, k);
			const hybP = precisionAtK(hybContents, test.relevant, k);
			ftsRecall += ftsR;
			hybRecall += hybR;
			ftsPrecision += ftsP;
			hybPrecision += hybP;
			const marker = hybR > ftsR ? "↑" : hybR < ftsR ? "↓" : "=";
			console.log(`  [${marker}] "${test.query}"  fts recall=${ftsR.toFixed(2)} prec=${ftsP.toFixed(2)}  hybrid recall=${hybR.toFixed(2)} prec=${hybP.toFixed(2)}`);
		}
		const n = evals.length;
		console.log(`\n[quant] mean recall@${k}    fts=${(ftsRecall / n).toFixed(3)}  hybrid=${(hybRecall / n).toFixed(3)}`);
		console.log(`[quant] mean precision@${k} fts=${(ftsPrecision / n).toFixed(3)}  hybrid=${(hybPrecision / n).toFixed(3)}`);

		console.log("\n[fail-mode] LLM down (port 1):");
		const downSettings = Settings.isolated({
			"memory.backend": "nexus",
			"nexus.llm.enabled": true,
			"nexus.llm.provider": "openai-compatible",
			"nexus.llm.baseUrl": "http://127.0.0.1:1",
			"nexus.llm.model": "ghost-model",
		});
		const downClient = createNexusLlmClient(loadNexusConfig(downSettings), { timeoutMs: 800, retries: 0 });
		const downResult = await downClient!.complete({ messages: [{ role: "user", content: "hi" }], maxTokens: 4 });
		console.log("  result:", downResult);

		console.log("\n[fail-mode] LLM returns garbage non-JSON for completeJson:");
		const garbageFetch = async () =>
			new Response(JSON.stringify({ choices: [{ message: { content: "hi there, not json at all sorry" } }] }), { status: 200, headers: { "content-type": "application/json" } });
		const garbageClient = createNexusLlmClient(loadNexusConfig(Settings.isolated({
			"memory.backend": "nexus",
			"nexus.llm.enabled": true,
			"nexus.llm.provider": "openai-compatible",
			"nexus.llm.baseUrl": "http://127.0.0.1:9999",
			"nexus.llm.model": "g",
		})), { fetch: garbageFetch as unknown as typeof fetch });
		const garbageResult = await garbageClient!.completeJson<{ x: number }>({
			messages: [{ role: "user", content: "x" }],
			validate: (value): value is { x: number } => typeof (value as { x?: unknown })?.x === "number",
		});
		console.log("  result:", garbageResult);

		console.log("\n[fail-mode] pipeline with LLM down + embeddings up still creates memories via heuristic:");
		const failAgentDir = path.join(os.tmpdir(), `nexus-fail-${Date.now()}`);
		const failCwd = path.join(os.tmpdir(), `nexus-fail-cwd-${Date.now()}`);
		await fs.mkdir(path.join(failAgentDir, "sessions"), { recursive: true });
		await fs.mkdir(failCwd, { recursive: true });
		await Bun.write(
			path.join(failAgentDir, "sessions", "thr.jsonl"),
			[
				{ type: "session", id: "thr-fail", cwd: failCwd },
				{ type: "message", message: { role: "user", content: "Always reply in concise Korean by default." } },
				{ type: "message", message: { role: "assistant", content: "Run bun test before edits; memory.backend should be nexus." } },
				{ type: "message", message: { role: "user", content: "The build failed with error: dependency mismatch." } },
			].map(row => `${JSON.stringify(row)}\n`).join(""),
		);
		const failSettings = Settings.isolated({
			"memory.backend": "nexus",
			"nexus.llm.enabled": true,
			"nexus.llm.provider": "openai-compatible",
			"nexus.llm.baseUrl": "http://127.0.0.1:1",
			"nexus.llm.model": "ghost",
			"nexus.embeddings.enabled": true,
			"nexus.embeddings.provider": "ollama",
			"nexus.embeddings.baseUrl": process.env.NEXUS_LIVE_EMBED_URL ?? "http://127.0.0.1:11434",
			"nexus.embeddings.model": process.env.NEXUS_LIVE_EMBED_MODEL ?? "bge-m3",
			"nexus.dream.enabled": true,
			"nexus.maxLlmCalls": 3,
		});
		const failLlm = createNexusLlmClient(loadNexusConfig(failSettings), { timeoutMs: 500, retries: 0 });
		const failEmbed = createNexusEmbeddingClient(loadNexusConfig(failSettings), { timeoutMs: 30_000 });
		const failStore = new NexusStore({ agentDir: failAgentDir, cwd: failCwd });
		try {
			const failResult = await runNexusPipeline(failStore, failSettings, { llmClient: failLlm, embeddingClient: failEmbed });
			console.log("  pipeline result:", failResult);
			const entries = failStore.list({ scope: "all", limit: 20 });
			for (const e of entries) console.log(`    · [${e.confidence}] ${e.content.slice(0, 80)}`);
		} finally {
			failStore.close();
			await fs.rm(failAgentDir, { recursive: true, force: true });
			await fs.rm(failCwd, { recursive: true, force: true });
		}
	} finally {
		store.close();
		await fs.rm(agentDir, { recursive: true, force: true });
		await fs.rm(cwd, { recursive: true, force: true });
	}
}

await main();
