import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { DefaultResourceLoader } from "../../../src/core/resource-loader.ts";

describe("default global extension shims", () => {
	let tempDir: string;
	let agentDir: string;
	let previousAgentDir: string | undefined;

	beforeEach(() => {
		tempDir = join(tmpdir(), `senpi-default-extension-shims-${Date.now()}-${Math.random().toString(36).slice(2)}`);
		agentDir = join(tempDir, "agent");
		previousAgentDir = process.env.SENPI_CODING_AGENT_DIR;
		process.env.SENPI_CODING_AGENT_DIR = agentDir;
		mkdirSync(join(agentDir, "extensions"), { recursive: true });
	});

	afterEach(() => {
		if (previousAgentDir === undefined) {
			delete process.env.SENPI_CODING_AGENT_DIR;
		} else {
			process.env.SENPI_CODING_AGENT_DIR = previousAgentDir;
		}
		if (existsSync(tempDir)) {
			rmSync(tempDir, { recursive: true, force: true });
		}
	});

	it("Given a stale generated shim, when resources reload, then the shim points at the current package", async () => {
		const shimPath = join(agentDir, "extensions", "diff.js");
		writeFileSync(
			shimPath,
			'// Generated by pi-coding-agent. Delete this file to stop loading the default global extension.\nexport { default } from "file:///Users/yeongyu/local-workspaces/senpi-mono/packages/coding-agent/src/core/extensions/builtin/diff.ts";\n',
			"utf-8",
		);
		const loader = new DefaultResourceLoader({
			cwd: tempDir,
			agentDir,
			noExtensions: true,
			noSkills: true,
			noPromptTemplates: true,
			noThemes: true,
			noContextFiles: true,
		});

		await loader.reload();

		const shim = readFileSync(shimPath, "utf-8");
		expect(shim).toContain("/src/core/extensions/builtin/diff.ts");
		expect(shim).not.toContain("senpi-mono");
	});
});
