import { createHash } from "node:crypto";
import * as fs from "node:fs/promises";
import * as path from "node:path";
import { descriptorFromLazyAgentTool } from "../agi/agent-tool-adapter";
import type { CapabilityLease } from "../agi/capability-lease";
import type {
	EvidenceRequirement,
	EvidenceVerificationResult,
	MissionEvidenceVerifier,
} from "../agi/evidence-verifier";
import { AgiGovernance } from "../agi/governance";
import { RegistryRoleExecutor, type RoleExecutor } from "../agi/role-executor";
import { AgiRuntime, type AgiRuntimeDeps, type AgiRuntimePlanner, type AgiRuntimeTickResult } from "../agi/runtime";
import { GitWorktreeSandboxManager } from "../agi/sandbox-manager";
import type { ContractiblePlanStep, ObjectiveContract, RuntimeAction, RuntimeActionStatus } from "../autonomy";
import { ObjectiveScheduler } from "../autonomy/scheduler";
import { ObjectiveStore } from "../autonomy/store";
import { Settings } from "../config/settings";
import { MissionRuntimeImpl } from "../mission/core/mission-runtime";
import { MissionStore } from "../mission/store";
import { createTools, type ToolSession } from "../tools";
import { SessionToolGateway } from "../tools/gateway/session-gateway";
import { ToolRegistry } from "../tools/registry/tool-registry";

/**
 * End-to-end strict AGI mutation runtime harness.
 *
 * Drives the full governed control flow against an isolated git repository:
 * objective contract → role routing → governed executor dispatch → capability
 * lease enforcement → production `write` descriptor selection → git worktree
 * sandbox cwd → real file mutation → machine-derived evidence verification →
 * accept (apply to main) on pass / rollback on fail → mission-state persistence.
 *
 * It exercises the production substrate (no synthetic descriptors) and is reused
 * both by deterministic tests and by the CI-ready AGI runtime eval.
 */

export type MutationApprovalMode = "approve" | "reject" | "pending" | "none";

export interface MutationRuntimeOptions {
	/** Isolated git repository root the runtime forks worktrees from. */
	repoCwd: string;
	/** Directory under which sandbox worktrees are created. */
	sandboxRoot: string;
	/** Mission/objective durable store path. */
	dbPath: string;
	/** Repo-relative file the mutation targets. */
	targetPath: string;
	/** Content the production `write` descriptor will produce in the sandbox. */
	mutationContent: string;
	/** Deterministic marker the captured diff must contain to verify as pass. */
	expectedMarker: string;
	/** Governance approval disposition for the mutating action. Default "approve". */
	approval?: MutationApprovalMode;
	/** When true, the mission is emergency-stopped before the runtime ticks. */
	emergencyStop?: boolean;
	settings: Settings;
	now?: () => number;
}

export interface MutationRuntimeResult {
	missionId: string;
	objectiveId: string;
	actionId: string;
	tick: AgiRuntimeTickResult;
	actionStatus?: RuntimeActionStatus;
	leaseAllowedTools?: string[];
	missionState?: string;
	/** Target file content in the MAIN repo after the tick (sandbox is disposed). */
	mainContent: string;
	/** True when the main working tree + index are clean (no leaked mutation). */
	mainClean: boolean;
	/** Runtime event types emitted during the tick, in order. */
	eventTypes: string[];
	evidenceRefs: string[];
}

const STEP_ID = "mutate-step";

export class StrictMutationRuntime {
	readonly #options: Required<Omit<MutationRuntimeOptions, "now" | "approval" | "emergencyStop">> & {
		now: () => number;
		approval: MutationApprovalMode;
		emergencyStop: boolean;
	};
	#missionStore: MissionStore;
	#objectiveStore: ObjectiveStore;
	#missionRuntime: MissionRuntimeImpl;
	#missionId = "";
	readonly #objectiveId = "objective-mutation-runtime";

	private constructor(options: MutationRuntimeOptions) {
		this.#options = {
			repoCwd: options.repoCwd,
			sandboxRoot: options.sandboxRoot,
			dbPath: options.dbPath,
			targetPath: options.targetPath,
			mutationContent: options.mutationContent,
			expectedMarker: options.expectedMarker,
			settings: options.settings,
			now: options.now ?? Date.now,
			approval: options.approval ?? "approve",
			emergencyStop: options.emergencyStop ?? false,
		};
		this.#missionStore = new MissionStore(options.dbPath);
		this.#objectiveStore = new ObjectiveStore(options.dbPath);
		this.#missionRuntime = new MissionRuntimeImpl({ store: this.#missionStore, autonomyProfile: "strict" });
	}

	static async create(options: MutationRuntimeOptions): Promise<StrictMutationRuntime> {
		// The production write descriptor reads the global Settings singleton (e.g.
		// edit.blockAutoGenerated). Initialize it once against the target repo; init
		// is idempotent and a no-op when the CLI already initialized it at startup.
		await Settings.init({ cwd: options.repoCwd });
		const runtime = new StrictMutationRuntime(options);
		await runtime.#prepare();
		return runtime;
	}

	get missionId(): string {
		return this.#missionId;
	}

	get actionId(): string {
		return `${this.#missionId}:${STEP_ID}`;
	}

	/** Close stores and recreate them against the same db to simulate a process restart. */
	reopen(): void {
		this.#missionRuntime.close();
		this.#objectiveStore.close();
		this.#missionStore.close();
		this.#missionStore = new MissionStore(this.#options.dbPath);
		this.#objectiveStore = new ObjectiveStore(this.#options.dbPath);
		this.#missionRuntime = new MissionRuntimeImpl({ store: this.#missionStore, autonomyProfile: "strict" });
	}

	close(): void {
		this.#missionRuntime.close();
		this.#objectiveStore.close();
		this.#missionStore.close();
	}

	async #prepare(): Promise<void> {
		this.#objectiveStore.create({
			id: this.#objectiveId,
			title: "Apply governed sandboxed mutation",
			metricTargets: [{ metric: "applied_mutations", target: 1, direction: "up" }],
			budget: {},
			guardrails: { requireHumanForApply: false, maxAutoSubgoalsPerDay: 1, forbiddenScopes: [] },
		});
		const mission = this.#missionStore.createMission({
			title: "Apply governed sandboxed mutation",
			objective: "Apply governed sandboxed mutation",
			objectiveId: this.#objectiveId,
			briefId: null,
			decisionId: null,
			riskLevel: "high",
			state: "executing",
			confidence: null,
			snapshotRef: null,
			mode: "interactive",
			intent: "code_change",
			lifecycle: "executing",
		});
		this.#missionId = mission.id;
		this.#missionStore.saveAcceptanceCriteria(mission.id, [
			{ id: "criterion-mutation", description: "Sandboxed mutation lands the expected change", satisfied: false },
		]);

		// Pre-seed governance approval keyed to the deterministic action id so the
		// HIGH-risk mutation lease can (or cannot) clear AgiGovernance.assertLeaseMayRun.
		if (this.#options.approval !== "none") {
			const governance = new AgiGovernance({ store: this.#missionStore, now: this.#options.now });
			const request = governance.requestApproval(
				{ id: this.actionId, missionId: mission.id } as RuntimeAction,
				"high",
			);
			if (this.#options.approval === "approve") governance.approve(request.id, "operator");
			else if (this.#options.approval === "reject") governance.reject(request.id, "operator", "mutation rejected");
			// "pending" leaves the request undecided so the lease cannot clear governance.
		}

		if (this.#options.emergencyStop) {
			this.#missionStore.recordAgiEmergencyStop(mission.id, "operator emergency stop before mutation");
		}
	}

	async tick(): Promise<MutationRuntimeResult> {
		const baselineRef = (await git(this.#options.repoCwd, ["rev-parse", "HEAD"])).trim();
		const approvalIdentity =
			this.#options.approval === "none"
				? undefined
				: {
						approvalId: `approval-${this.actionId}`,
						approvedBy: "operator",
						approvedAt: this.#options.now(),
						reason: "mutation approved",
					};

		const scheduler = new ObjectiveScheduler({
			store: this.#objectiveStore,
			missionRuntime: this.#missionRuntime,
			classifyContinuation: ({ missionId }) =>
				missionId ? { kind: "continue", reason: "missing_requirements" } : { kind: "none", reason: "no_mission" },
			findMissionForObjective: () => this.#missionId,
			resumeMission: () => undefined,
			holdObjective: () => undefined,
			now: this.#options.now,
		});
		// The scheduler emits a `resume-mission` decision; the AgiRuntime only acts on
		// schedule-mission/resume-mission, so map the objective to the prepared mission.
		const wrappedScheduler = {
			tick: async () => {
				await scheduler.tick();
				return [{ objectiveId: this.#objectiveId, kind: "resume-mission", missionId: this.#missionId }];
			},
		};

		const sandbox = new GitWorktreeSandboxManager({ rootDir: this.#options.sandboxRoot, now: this.#options.now });
		const verifier = new SandboxDiffVerifier(this.#missionStore, this.#options.expectedMarker);

		const runtime = new AgiRuntime({
			scheduler: wrappedScheduler,
			objectives: this.#objectiveStore,
			missionRuntime: this.#missionRuntime,
			compilerModel: new MutationCompilerModel(this.#options.targetPath),
			planner: new MutationPlanner(this.#options.targetPath),
			leaseIssuer: new MutationLeaseIssuer({ baselineRef, approval: approvalIdentity }),
			toolGateway: new SessionToolGateway({
				permissionMode: "lease",
				leaseDeps: {
					getMission: missionId => this.#missionRuntime.tryGet(missionId),
					getProposal: proposalId => this.#missionStore.getProposal(proposalId),
					now: this.#options.now,
				},
			}),
			verifier,
			store: this.#missionStore,
			governance: new AgiGovernance({ store: this.#missionStore, now: this.#options.now }),
			executor: await this.#createMutationExecutor(),
			sandbox,
			repoCwd: this.#options.repoCwd,
		} satisfies AgiRuntimeDeps);

		const tick = await runtime.tick();

		const action = this.#missionStore.getRuntimeAction(this.actionId);
		const mainContent = await readMaybe(path.join(this.#options.repoCwd, this.#options.targetPath));
		const status = (await git(this.#options.repoCwd, ["status", "--porcelain"])).trim();
		const events = this.#missionStore.listRuntimeEvents(this.#missionId);

		return {
			missionId: this.#missionId,
			objectiveId: this.#objectiveId,
			actionId: this.actionId,
			tick,
			actionStatus: action?.status,
			leaseAllowedTools: action?.lease?.allowedTools,
			missionState: this.#missionStore.getMission(this.#missionId)?.state,
			mainContent,
			mainClean: status.length === 0,
			eventTypes: events.map(event => event.type),
			evidenceRefs: events.flatMap(event => event.evidenceRefs),
		};
	}

	async #createMutationExecutor(): Promise<RoleExecutor> {
		const settings = this.#options.settings;
		const targetPath = this.#options.targetPath;
		const mutationContent = this.#options.mutationContent;
		const writeDescriptor = descriptorFromLazyAgentTool(
			"write",
			async (cwd: string) => {
				const session = mutationToolSession(cwd, settings);
				const [tool] = await createTools(session, ["write"]);
				if (!tool) throw new Error("write tool unavailable");
				return tool;
			},
			{ label: "Write", parameters: { path: "string", content: "string" } },
		);
		const registry = new ToolRegistry();
		registry.register(writeDescriptor);

		return new RegistryRoleExecutor({
			registry,
			buildInput: () => ({ path: targetPath, content: mutationContent }),
			buildContext: ({ action, lease, sandboxWorkspace }) => ({
				cwd: sandboxWorkspace?.cwd,
				capabilityLease: lease,
				actionId: action.id,
				planStepId: action.stepId,
				mutationScope: lease.mutationScope.allowedPaths,
				agentRole: "orchestrator",
				session: settings,
			}),
		});
	}
}

function mutationToolSession(cwd: string, settings: Settings): ToolSession {
	return {
		cwd,
		hasUI: false,
		skipPythonPreflight: true,
		enableLsp: false,
		settings,
		getSessionFile: () => null,
		getSessionSpawns: () => "*",
	};
}

class MutationCompilerModel {
	readonly #targetPath: string;
	constructor(targetPath: string) {
		this.#targetPath = targetPath;
	}

	async compile(input: {
		goal: string;
		criteria: string[];
		constraints: string[];
		mode?: string;
	}): Promise<ObjectiveContract> {
		const criteria = input.criteria.length > 0 ? input.criteria : ["Sandboxed mutation lands the expected change."];
		const acceptanceCriteria = criteria.map((description, index) => ({
			id: `criterion-${index + 1}`,
			description,
			required: true,
			evidenceKinds: ["source_diff" as const],
			ownerRole: "Verifier" as const,
			verification: "deterministic" as const,
		}));
		return {
			id: stableId("contract", [input.goal, this.#targetPath, input.mode ?? "supervised"]),
			objective: input.goal,
			nonGoals: ["Do not mutate the main repository without sandbox isolation and verification."],
			acceptanceCriteria,
			requiredEvidence: Object.fromEntries(acceptanceCriteria.map(c => [c.id, c.evidenceKinds])),
			scopeGuard: {
				include: [this.#targetPath],
				exclude: [],
				allowedCommands: [],
				forbiddenActions: ["deploy", "operate-infrastructure"],
			},
			budgetGuard: { maxRuntimeActions: 1, maxRetriesPerAction: 0, maxParallelActions: 1 },
			autonomyMode: "supervised",
			risk: "high",
			freshnessPolicy: { researchRequired: false },
			rolePolicy: {
				capabilities: [
					{
						role: "Builder",
						modelRole: "Builder",
						canRead: true,
						canWriteRepository: true,
						canRunCommands: false,
						canOperateInfrastructure: false,
						canApproveCompletion: false,
						allowedTools: ["read", "write"],
					},
					{
						role: "Verifier",
						modelRole: "Verifier",
						canRead: true,
						canWriteRepository: false,
						canRunCommands: false,
						canOperateInfrastructure: false,
						canApproveCompletion: true,
						allowedTools: ["read"],
					},
				],
				defaultRoleByStepKind: { implementation: "Builder", verify: "Verifier", default: "Builder" },
				requireReviewerForRisk: [],
				requireSecurityFor: [],
				requireSreFor: [],
			},
		};
	}
}

class MutationPlanner implements AgiRuntimePlanner {
	readonly #targetPath: string;
	constructor(targetPath: string) {
		this.#targetPath = targetPath;
	}

	async planMission(input: {
		mission: { id: string; objective: string };
		contract: ObjectiveContract;
	}): Promise<{ id: string; steps: ContractiblePlanStep[] }> {
		const step: ContractiblePlanStep = {
			id: STEP_ID,
			kind: "implementation",
			description: `Apply sandboxed mutation to ${this.#targetPath}`,
			roleHint: "Builder",
			touches: [this.#targetPath],
			requiresWrite: true,
			requiresCommands: false,
			requiresInfrastructure: false,
			acceptanceCriteria: input.contract.acceptanceCriteria.map(c => c.id),
			requiredEvidence: ["source_diff"],
		};
		return { id: stableId("plan", [input.mission.id, input.contract.id]), steps: [step] };
	}
}

class MutationLeaseIssuer {
	readonly #baselineRef: string;
	readonly #approval: CapabilityLease["approval"];
	constructor(input: { baselineRef: string; approval: CapabilityLease["approval"] }) {
		this.#baselineRef = input.baselineRef;
		this.#approval = input.approval;
	}

	issue(input: { contract: ObjectiveContract; action: RuntimeAction }): CapabilityLease {
		const issuedAt = Date.now();
		return {
			leaseId: stableId("lease", [input.action.id, String(issuedAt)]),
			missionId: input.action.missionId,
			objectiveContractId: input.action.objectiveContractId,
			planId: input.action.planId,
			planStepId: input.action.stepId,
			actionId: input.action.id,
			mode: "interactive",
			actorRole: input.action.role,
			allowedTools: ["write"],
			allowedRisk: "HIGH",
			mutationScope: {
				allowedPaths: input.action.scopeGuard.include,
				deniedPaths: input.action.scopeGuard.exclude,
				allowedServices: [],
				allowedDataClasses: [],
			},
			budget: { maxToolCalls: 1, maxRetries: 0, timeoutMs: 30_000 },
			...(this.#approval ? { approval: this.#approval } : {}),
			sandbox: { mode: "isolated-worktree", baselineRef: this.#baselineRef, rollbackRefs: [this.#baselineRef] },
			evidenceContract: { requiredEventTypes: ["tool.requested", "tool.completed"], requiredEvidenceRefs: [] },
			issuedAt,
			expiresAt: issuedAt + 15 * 60_000,
		};
	}
}

/**
 * Deterministic, machine-derived mutation verifier. It reads the actual captured
 * sandbox diff produced by the production tool and passes only when the diff
 * contains the expected marker — never trusting an agent self-report.
 */
class SandboxDiffVerifier implements MissionEvidenceVerifier {
	readonly #store: MissionStore;
	readonly #expectedMarker: string;
	constructor(store: MissionStore, expectedMarker: string) {
		this.#store = store;
		this.#expectedMarker = expectedMarker;
	}

	async verifyMission(input: {
		missionId: string;
		objectiveContractId?: string;
		requirements: EvidenceRequirement[];
	}): Promise<EvidenceVerificationResult> {
		const events = this.#store.listRuntimeEvents(input.missionId);
		const diffEvent = [...events].reverse().find(event => event.type === "sandbox.diff_captured");
		const diffRef = typeof diffEvent?.payload.diffRef === "string" ? diffEvent.payload.diffRef : undefined;
		const diff = diffRef ? await readMaybe(diffRef) : "";
		const passed = diff.includes(this.#expectedMarker);
		const checkedAt = Date.now();
		const status = passed ? "pass" : "fail";
		const evidenceRefs = diffRef ? [diffRef] : [];
		const result: EvidenceVerificationResult = {
			missionId: input.missionId,
			...(input.objectiveContractId ? { objectiveContractId: input.objectiveContractId } : {}),
			status,
			criteria: input.requirements.map(requirement => ({
				criterionId: requirement.criterionId,
				status,
				evidenceRefs,
				...(passed ? {} : { reason: `captured diff does not contain expected marker "${this.#expectedMarker}"` }),
			})),
			checkedAt,
		};
		this.#store.appendRuntimeEvent({
			missionId: input.missionId,
			streamId: `evidence:${input.missionId}`,
			type: "evidence.verified",
			actor: "agi.sandbox-diff-verifier",
			payload: result as unknown as Record<string, unknown>,
			evidenceRefs,
			idempotencyKey: `evidence:${input.objectiveContractId ?? "mission"}:${checkedAt}`,
		});
		return result;
	}
}

async function readMaybe(filePath: string): Promise<string> {
	try {
		return await fs.readFile(filePath, "utf8");
	} catch {
		return "";
	}
}

async function git(cwd: string, args: string[]): Promise<string> {
	const proc = Bun.spawn(["git", ...args], { cwd, stdin: "ignore", stdout: "pipe", stderr: "pipe" });
	const [stdout, stderr, exitCode] = await Promise.all([
		new Response(proc.stdout).text(),
		new Response(proc.stderr).text(),
		proc.exited,
	]);
	if (exitCode !== 0) throw new Error(`git ${args.join(" ")} failed: ${stderr.trim() || stdout.trim()}`);
	return stdout;
}

function stableId(prefix: string, parts: string[]): string {
	const hash = createHash("sha256").update(parts.join("\0")).digest("hex").slice(0, 12);
	return `${prefix}-${hash}`;
}
